version: '3.8'

services:
  cyberchef:
    build: .
    ports:
      - "8081:80"
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "ip route del default && nginx -g 'daemon off;'"
    dns:
      - 127.0.0.1  # optional, DNS block
