version: '3.8'

services:
  cyberchef:
    build: .
    ports:
      - "8081:80"
    networks:
      - isolated_net
    dns:
      - 127.0.0.1

networks:
  isolated_net:
    driver: bridge
    internal: true
